/**
 * Fandomly Chain contract addresses and configuration.
 * Auto-generated by deploy-all.mjs on 2026-03-09T21:28:42.557Z
 */

export const FANDOMLY_CHAIN = {
  id: 89197,
  name: 'Fandomly Chain',
  nativeCurrency: { name: 'FAN', symbol: 'FAN', decimals: 18 },
  rpcUrl:
    ((typeof process !== 'undefined' ? process.env.VITE_FANDOMLY_RPC_URL : undefined) ?? '').split(
      /\s/
    )[0] ||
    'https://nodes-prod.18.182.4.86.sslip.io/ext/bc/2Ux71YgdfbcyTCoDYFEkE1Qy9nYpSQyd1it4f953ZTQAaJLB7t/rpc',
  blockExplorer:
    'https://subnets-test.avax.network/subnets/2vPvpLkRNwNVhyRLH4JuDSsdYnjFzc68MFVXGAPqTNZ148SfFL',
  testnet: true,
} as const;

export const CONTRACTS = {
  // Core contracts (v2 — audit-fixed)
  ReputationRegistry: '0x9a0f05d971bb5bb908fc45ce51e948712265e518',
  CreatorTokenFactory: '0xd8d942262792dd1d794b52137f93359ef530dcd9',
  FanStaking: '0xfca2572ed381cfc8d7cca205f9da0b4e2b7d6d89',
  // NFT contracts
  FandomlyBadge: '0x4ad8bbb28fba6beaee346e61ac03d18903331356',
  FandomlyNFT: '0x1cfb20643302b88c1291a950f263b5c17d8f7aa6',
  CreatorCollectionFactory: '0xc0e2fc4eac83b421856527992de427a01aeeea7b',
} as const;

export const DEPLOYER_ADDRESS = '0x95A6bEb968633D1440e89F462a133519808f8015' as const;
